name: Elixir CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir-version: [1.15.4]  # Change this according to your Elixir version
        otp-version: [26]     # Specify OTP (Erlang) version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku
      run: echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

    - name: Deploy to Heroku
      run: git push heroku master
